/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.spring.dependency-management") version "1.1.0"
    id("org.springframework.boot") version "2.5.7"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-oauth2-client:2.2.2.RELEASE")
    api("org.springframework.boot:spring-boot-starter-web:2.2.2.RELEASE")
    api("org.webjars:jquery:2.1.0")
    api("org.webjars:bootstrap:3.2.0")
    api("org.webjars:webjars-locator-core:0.41")
    implementation("org.webjars:URI.js:1.14.1")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.2.2.RELEASE")

}
tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes["Main-Class"] = "com.gitHibAutharization.GitHibAutharization.SocialLogin"
    }
    from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) })

}
group = "com.social-login-microservise"
version = "0.0.1-SNAPSHOT"
description = "social-login-microservise"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
